import { EOL } from "os";
import dotenv from "dotenv";
import path from "path";
import fs from "fs";

export const generate = (env = process.env.NODE_ENV) => {
  const base = dotenv.parse(fs.readFileSync(path.join(process.cwd(), ".env")));
  const overwritePath = path.join(process.cwd(), `.env${env ? `.${env}` : ""}`);
  const overwrite = dotenv.parse(fs.readFileSync(overwritePath));

  Object.keys(base).forEach((key) => {
    if (overwrite[key]) base[key] = overwrite[key];
    else if (!base[key])
      throw new Error(`${key} must set in ${overwritePath}.`);
  });

  return (
    [
      "// Generated by dotenv-generator.",
      `export const env = ${JSON.stringify(base, null, 2)};`,
    ].join(EOL) + EOL
  );
};
